<?php

return [
    'default' => '1',
    'data' => [
        '1' => 'United States/Canada',
        '7' => 'Россия/Қазақстан',
        '20' => 'مصر',
        '27' => 'South Africa',
        '30' => 'Ελλάδα',
        '31' => 'Nederland',
        '32' => 'België/Belgique/Belgien',
        '33' => 'France',
        '34' => 'España',
        '36' => 'Magyarország',
        '39' => 'Italia',
        '40' => 'România',
        '41' => 'Schweiz/Suisse/Svizzera',
        '43' => 'Österreich',
        '44' => 'United Kingdom',
        '45' => 'Danmark',
        '46' => 'Sverige',
        '47' => 'Norge',
        '48' => 'Polska',
        '49' => 'Deutschland',
        '52' => 'México',
        '54' => 'Argentina',
        '55' => 'Brasil',
        '60' => 'Malaysia',
        '61' => 'Australia',
        '62' => 'Indonesia',
        '63' => 'Pilipinas',
        '64' => 'Aotearoa/New Zealand',
        '65' => 'Singapura',
        '66' => 'ประเทศไทย',
        '81' => '日本',
        '82' => '대한민국',
        '84' => 'Việt Nam',
        '86' => '中国大陆',
        '90' => 'Türkiye',
        '91' => 'भारत/India',
        '351' => 'Portugal',
        '358' => 'Suomi',
        '852' => '中國香港',
        '886' => '臺灣',
    ],
];
